apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    name: mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-pod
  template:
    metadata:
    name: mysql-pod
      labels:
        name: mysql-pod
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
              secretKeyRef:
              #key-value pair
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
              secretKeyRef:
              #key-value pair
        envFrom:
        - configMapRef:
            #name of the configmap  
        volumeMounts: 
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim


       